In [1]:
import numpy as np
import random as rd

In [2]:
# count time 
import time



In [3]:
# timer start
start_time = time.time()
a = np.zeros((3, 3))
for i in range(1000):
    a += np.random.rand(3, 3)
t = time.time() - start_time
print(t)

0.004293918609619141


In [4]:

start_time = time.time()
a = np.zeros((3, 3))
for k in range(1000):
    for i in range(3):
        for j in range(3):
            a[i][j] += rd.random()
time = time.time() - start_time
print(time)

0.005123138427734375


Slight difference in performance. Not worthwhile to modify the original program 

In [5]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.diag(mat.diagonal())
mat2 = mat.copy()
mat2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
mat1 = np.array([[1, 1], [1, -1]])
mat2 = mat1.copy()

mat1**3

array([[ 1,  1],
       [ 1, -1]])

In [2]:
fact = 1
for i in range(1, 131):
    fact *= i
print(fact)

6466855489220473672507304395536485253155359447828049608975952322944781961185526165512707047229268452925683969240398027149120740074042105844737747799459310029635780991774612983803150965145600000000000000000000000000000000


In [6]:
import numpy as np
arr = np.array([1, 2, 3])
sum(arr**2)

14

In [24]:
x = np.random.rand(2,3)

In [26]:
r = np.random.rand(2, 3)
print(r)

[[0.82243227 0.75505562 0.87063712]
 [0.5250173  0.76977074 0.35020549]]


In [31]:
alpha = 1
wf = np.sum(np.exp(-alpha * np.sum(r**2)))
wf

0.050019274418974705